# Generated by Django 3.1.7 on 2021-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_address2',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
