# Generated by Django 3.1.7 on 2021-04-13 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_orderstatus_payoutstatus_sourceorder_sourcetraffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('warehouse', models.CharField(max_length=255, null=True)),
                ('consignment_note', models.CharField(max_length=255, null=True)),
                ('settings_delivery', models.CharField(max_length=255, null=True)),
                ('prepayment', models.CharField(max_length=255, null=True)),
                ('cash_on_delivery', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_orders', to=settings.AUTH_USER_MODEL)),
                ('order_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.orderstatus')),
                ('payout_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.payoutstatus')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.product')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.provider')),
                ('source_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.sourceorder')),
                ('source_traffic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.sourcetraffic')),
            ],
        ),
    ]
