# Generated by Django 3.1.7 on 2021-04-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210414_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.orderstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payout_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.payoutstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.provider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.sourceorder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_traffic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.sourcetraffic'),
        ),
    ]
