# Generated by Django 3.1.7 on 2021-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210415_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='income',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
