# Generated by Django 3.1.7 on 2021-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210418_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='income',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
