# Generated by Django 3.1.7 on 2021-04-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210418_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prepayment',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
